// <auto-generated />
using System;
using System.Collections.Generic;
using MediHub.Web.DatabaseContext.AppDbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediHub.Web.Migrations
{
    [DbContext(typeof(MediHubContext))]
    [Migration("20250729173803_[updateDeleteName]")]
    partial class updateDeleteName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediHub.Web.Models.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppraisalFile")
                        .HasColumnType("text")
                        .HasColumnName("appraisal_file");

                    b.Property<DateTime?>("CalibrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calibration_date");

                    b.Property<DateTime?>("CalibrationNextDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calibration_next_date");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<List<string>>("DeviceAvatar")
                        .HasColumnType("text[]")
                        .HasColumnName("device_avatar");

                    b.Property<string>("DeviceCode")
                        .HasColumnType("text")
                        .HasColumnName("device_code");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<int>("DeviceStatus")
                        .HasColumnType("integer")
                        .HasColumnName("device_status");

                    b.Property<string>("DeviceUsageInstructions")
                        .HasColumnType("text")
                        .HasColumnName("device_usage_instructions");

                    b.Property<string>("EngineerInfo")
                        .HasColumnType("text")
                        .HasColumnName("engineer_info");

                    b.Property<string>("EngineerPhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("engineer_phonenumber");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FunctionName")
                        .HasColumnType("text")
                        .HasColumnName("function_name");

                    b.Property<string>("ImportSource")
                        .HasColumnType("text")
                        .HasColumnName("import_source");

                    b.Property<string>("InstallationContract")
                        .HasColumnType("text")
                        .HasColumnName("installation_contract");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LabUsage")
                        .HasColumnType("text")
                        .HasColumnName("lab_usage");

                    b.Property<int>("MachineStatus")
                        .HasColumnType("integer")
                        .HasColumnName("machine_status");

                    b.Property<DateTime?>("MaintenanceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("maintenance_date");

                    b.Property<DateTime?>("MaintenanceNextDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("maintenance_next_date");

                    b.Property<int>("MaintenanceSchedule")
                        .HasColumnType("integer")
                        .HasColumnName("maintenance_schedule");

                    b.Property<string>("ManagerInfo")
                        .HasColumnType("text")
                        .HasColumnName("manager_info");

                    b.Property<string>("ManagerPhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("manager_phonenumber");

                    b.Property<string>("ManufacturerCountry")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer_country");

                    b.Property<int>("ManufacturerName")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturer_name");

                    b.Property<int>("ManufacturingYear")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_year");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("ReplaceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replace_date");

                    b.Property<DateTime?>("ReplaceNextDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replace_next_date");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("UsageDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usage_date");

                    b.HasKey("Id");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("MediHub.Web.Models.MaintenanceRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceID")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("FileLinks")
                        .HasColumnType("text")
                        .HasColumnName("file_links");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("MaintaindDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("maintaind_date");

                    b.Property<string>("MaintenanceDate")
                        .HasColumnType("text")
                        .HasColumnName("maintenance_date");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TypeOfMaintenance")
                        .HasColumnType("integer")
                        .HasColumnName("type_of_maintenance");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceRecordEntity");
                });

            modelBuilder.Entity("MediHub.Web.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsTokenValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_token_valid");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<DateTime?>("LastLogout")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_logout");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<List<string>>("Role")
                        .HasColumnType("text[]")
                        .HasColumnName("role");

                    b.Property<DateTime?>("TokenExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expiration");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
